# Copyright 2025 calm.wang@hotmail.com
# SPDX-License-Identifier: LGPL-3.0-only
version: '3.9'

networks:
  solana_indexer:

services:

  indexer:
    image: calmw/betcorgi_solana_indexer:0.0.6
    container_name: solana_indexer
    restart: always
    depends_on:
      - mysql
    environment:
      - PROGRAM_ID=FmoviYkRguNDJwX5vuj4NVPsy5Tzf9kZK23x6VTiE8P
      - RPC_WS=wss://api.devnet.solana.com
      - RPC_URL=https://api.devnet.solana.com
      - MYSQL_DATABASE=corgibet_solana
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=let_me_in_0x4f7d21e8ed
      - MYSQL_HOST=solana_indexer_mysql
      - MYSQL_PORT=3306
    networks:
      - solana_indexer
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  indexer_api:
    image: calmw/betcorgi_solana_indexer_api:0.0.5
    container_name: solana_indexer_api
    restart: always
    depends_on:
      - mysql
    environment:
      - MYSQL_DATABASE=corgibet_solana
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=let_me_in_0x4f7d21e8ed
      - MYSQL_HOST=solana_indexer_mysql
      - MYSQL_PORT=3306
    ports:
      - "8086:8080"
    networks:
      - solana_indexer
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  mysql:
    image: mysql:latest
    container_name: solana_indexer_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=let_me_in_0x4f7d21e8ed
      - MYSQL_DATABASE=corgibet_solana
    volumes:
      - ./mysql_data/data:/var/lib/mysql
      - ./mysql_data/conf:/etc/mysql/conf.d/
    networks:
      - solana_indexer
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G