FROM golang AS builder
WORKDIR /app
ADD . /app
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
RUN go mod tidy
RUN go build -o /solana_indexer_api cmd/service/main.go

FROM golang
WORKDIR /app
COPY --from=builder /solana_indexer_api /
RUN chmod +x /solana_indexer_api

ENTRYPOINT ["/solana_indexer_api"]